name: yatra_live
description: Real-time bus tracking system for Smart India Hackathon 2025

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.2
  
  # Simple Map for Demo - Zero Setup Required!
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  
  # State management  
  provider: ^6.1.1
  
  # Firebase (minimal for web compatibility)
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
